### PR TITLE
Fix: Create ciao channel in kubeflow

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <gaoce@caicloud.io>

**What this PR does / why we need it**:

Create ciao channel in Kubeflow

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

**Special notes for your reviewer**:

/cc @ddysher 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ddysher** [comment]
CI failed ...

**Comment by gaocegege** [comment]
gometalinter is not very stable, it fails to install some linters. I will fix it tomorrow

**Comment by ddysher** [comment]
/lgtm

?

**Pull request merged**
