### PR TITLE
README: Add gif demo

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <gaoce@caicloud.io>

**What this PR does / why we need it**:

Add demo in README

**Special notes for your reviewer**:

/cc @ddysher 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ddysher** [comment]
hmm, same old problem with coverall?

**Comment by gaocegege** [comment]
Yeah...

**Comment by ddysher** [comment]
manually merge

**Pull request merged**
